import {
  Account,
  Project,
  Client,
  Invoice,
  Transaction,
  Commission,
  FinancialAlert,
  BudgetPeriod,
  AuditLog,
} from '../types';

export const INITIAL_ACCOUNTS: Account[] = [
  {
    id: 'acc-bni',
    name: 'BNI Madagascar - Courant',
    type: 'BANK',
    provider: 'BNI Madagascar',
    accountNumber: '00004 01000 12345678901 45',
    balance: 42500000,
    initialBalance: 35000000,
    color: '#1E3A8A', // Deep Blue
    currency: 'MGA',
  },
  {
    id: 'acc-bmoi',
    name: 'BMOI - Réserve & Dépôt',
    type: 'BANK',
    provider: 'BMOI Madagascar',
    accountNumber: '00008 02000 98765432100 12',
    balance: 25000000,
    initialBalance: 20000000,
    color: '#4338CA', // Indigo
    currency: 'MGA',
  },
  {
    id: 'acc-mvola',
    name: 'MVola Business Pro',
    type: 'MOBILE_MONEY',
    provider: 'Telma / MVola',
    accountNumber: '+261 34 00 123 45',
    balance: 6850000,
    initialBalance: 4000000,
    color: '#059669', // Emerald
    currency: 'MGA',
  },
  {
    id: 'acc-orange',
    name: 'Orange Money Marchand',
    type: 'MOBILE_MONEY',
    provider: 'Orange Madagascar',
    accountNumber: '+261 32 00 987 65',
    balance: 3420000,
    initialBalance: 2500000,
    color: '#EA580C', // Orange
    currency: 'MGA',
  },
  {
    id: 'acc-cash',
    name: 'Caisse Centrale Espèces',
    type: 'CASH',
    provider: 'Coffre Siège Ankorondrano',
    balance: 1200000,
    initialBalance: 1500000,
    color: '#64748B', // Slate
    currency: 'MGA',
  },
];

export const INITIAL_CLIENTS: Client[] = [
  {
    id: 'cli-axian',
    name: 'Groupe Axian',
    company: 'Axian Telecom & Services',
    email: 'finance@axian-group.com',
    phone: '+261 20 22 555 01',
    address: 'Tour Redland, Ankorondrano, Antananarivo',
    nif: '4000123456',
    stat: '62011 11 2018 0 10234',
    totalBilled: 38000000,
    totalPaid: 25000000,
    outstandingBalance: 13000000,
    overdueDays: 0,
    status: 'GOOD',
  },
  {
    id: 'cli-star',
    name: 'Brasseries Star Madagascar',
    company: 'Groupe Castel / Star',
    email: 'compta@star.mg',
    phone: '+261 20 22 277 11',
    address: 'Route des Hydrocarbures, Andraharo',
    nif: '3000987654',
    stat: '11050 11 2015 0 00892',
    totalBilled: 45000000,
    totalPaid: 30000000,
    outstandingBalance: 15000000,
    overdueDays: 0,
    status: 'GOOD',
  },
  {
    id: 'cli-colas',
    name: 'Colas Madagascar',
    company: 'Colas BTP & Logistique',
    email: 'direction.finance@colas.mg',
    phone: '+261 20 22 421 00',
    address: 'Zone Industrielle Forello, Tanjombato',
    nif: '4000554433',
    stat: '42110 11 2010 0 00145',
    totalBilled: 24500000,
    totalPaid: 24500000,
    outstandingBalance: 0,
    overdueDays: 0,
    status: 'GOOD',
  },
  {
    id: 'cli-ravinala',
    name: 'Ravinala Airports',
    company: 'Aéroports de Madagascar',
    email: 'facturation@ravinala-airports.aero',
    phone: '+261 20 22 440 00',
    address: 'Aéroport International Ivato, Antananarivo',
    nif: '5000678912',
    stat: '52230 11 2019 0 00761',
    totalBilled: 12000000,
    totalPaid: 7200000,
    outstandingBalance: 4800000,
    overdueDays: 14,
    status: 'RISK',
  },
  {
    id: 'cli-agri',
    name: 'AgriTech Vakinankaratra',
    company: 'Coopérative Laitière d’Antsirabe',
    email: 'contact@agritech-vakin.mg',
    phone: '+261 34 11 223 34',
    address: 'Avenue de la Gare, Antsirabe',
    totalBilled: 18500000,
    totalPaid: 10000000,
    outstandingBalance: 8500000,
    overdueDays: 0,
    status: 'GOOD',
  },
];

export const INITIAL_PROJECTS: Project[] = [
  {
    id: 'prj-001',
    code: 'PRJ-2026-001',
    name: 'Portail E-Commerce & Marketplace B2B',
    category: 'ECOMMERCE',
    clientId: 'cli-axian',
    clientName: 'Groupe Axian',
    sellingPrice: 38000000,
    status: 'IN_PROGRESS',
    startDate: '2026-06-01',
    deliveryDate: '2026-09-30',
    progressPercent: 75,
    totalCollected: 25000000,
    description: 'Plateforme Next.js + NestJS avec paiement multi-opérateurs (MVola/Orange/Airtel/CB).',
    plannedCosts: [
      { id: 'c-1', label: 'Commission Lead Dev (Andry)', category: 'DEV_COMMISSION', plannedAmount: 7600000, realAmount: 6000000, isPaid: true, paidDate: '2026-07-15' },
      { id: 'c-2', label: 'Commission Commercial (Tahina)', category: 'SALES_COMMISSION', plannedAmount: 3800000, realAmount: 3800000, isPaid: true, paidDate: '2026-06-10' },
      { id: 'c-3', label: 'AWS Cloud & RDS PostgreSQL (3 mois)', category: 'CLOUD', plannedAmount: 1800000, realAmount: 1650000, isPaid: true, paidDate: '2026-08-01' },
      { id: 'c-4', label: 'Intégration Passerelle SMS & OTP', category: 'API', plannedAmount: 600000, realAmount: 580000, isPaid: true, paidDate: '2026-07-20' },
      { id: 'c-5', label: 'Audit Sécurité & Pentest externe', category: 'SUBCONTRACTING', plannedAmount: 2500000, realAmount: 2500000, isPaid: false },
    ],
    realCosts: [
      { id: 'c-1', label: 'Commission Lead Dev (Andry)', category: 'DEV_COMMISSION', plannedAmount: 7600000, realAmount: 6000000, isPaid: true, paidDate: '2026-07-15' },
      { id: 'c-2', label: 'Commission Commercial (Tahina)', category: 'SALES_COMMISSION', plannedAmount: 3800000, realAmount: 3800000, isPaid: true, paidDate: '2026-06-10' },
      { id: 'c-3', label: 'AWS Cloud & RDS PostgreSQL (3 mois)', category: 'CLOUD', plannedAmount: 1800000, realAmount: 1650000, isPaid: true, paidDate: '2026-08-01' },
      { id: 'c-4', label: 'Intégration Passerelle SMS & OTP', category: 'API', plannedAmount: 600000, realAmount: 580000, isPaid: true, paidDate: '2026-07-20' },
    ],
  },
  {
    id: 'prj-002',
    code: 'PRJ-2026-002',
    name: 'ERP Gestion Stocks & Logistique Brasserie',
    category: 'SOFTWARE',
    clientId: 'cli-star',
    clientName: 'Brasseries Star Madagascar',
    sellingPrice: 45000000,
    status: 'IN_PROGRESS',
    startDate: '2026-05-15',
    deliveryDate: '2026-10-15',
    progressPercent: 60,
    totalCollected: 30000000,
    description: 'Système centralisé de gestion des dépôts régionaux (Tamatave, Majunga, Fianarantsoa).',
    plannedCosts: [
      { id: 'c-10', label: 'Devs Fullstack (Mialy & Hery)', category: 'DEV_COMMISSION', plannedAmount: 10000000, realAmount: 8500000, isPaid: true },
      { id: 'c-11', label: 'Commission Commerciale', category: 'SALES_COMMISSION', plannedAmount: 4500000, realAmount: 4500000, isPaid: true },
      { id: 'c-12', label: 'Déplacements & Formation Usine Andraharo', category: 'TRAVEL', plannedAmount: 1500000, realAmount: 1200000, isPaid: true },
      { id: 'c-13', label: 'Licences Serveur & Docker Swarm', category: 'CLOUD', plannedAmount: 2200000, realAmount: 2850000, isPaid: true }, // Depassement
    ],
    realCosts: [
      { id: 'c-10', label: 'Devs Fullstack (Mialy & Hery)', category: 'DEV_COMMISSION', plannedAmount: 10000000, realAmount: 8500000, isPaid: true },
      { id: 'c-11', label: 'Commission Commerciale', category: 'SALES_COMMISSION', plannedAmount: 4500000, realAmount: 4500000, isPaid: true },
      { id: 'c-12', label: 'Déplacements & Formation Usine Andraharo', category: 'TRAVEL', plannedAmount: 1500000, realAmount: 1200000, isPaid: true },
      { id: 'c-13', label: 'Licences Serveur & Docker Swarm', category: 'CLOUD', plannedAmount: 2200000, realAmount: 2850000, isPaid: true },
    ],
  },
  {
    id: 'prj-003',
    code: 'PRJ-2026-003',
    name: 'App Mobile Suivi Flotte & Conducteurs',
    category: 'MOBILE_APP',
    clientId: 'cli-colas',
    clientName: 'Colas Madagascar',
    sellingPrice: 24500000,
    status: 'COMPLETED',
    startDate: '2026-03-01',
    deliveryDate: '2026-07-31',
    progressPercent: 100,
    totalCollected: 24500000,
    description: 'Application React Native avec suivi GPS offline-first et géolocalisation des engins.',
    plannedCosts: [
      { id: 'c-20', label: 'Développement Mobile (Andry)', category: 'DEV_COMMISSION', plannedAmount: 5000000, realAmount: 5000000, isPaid: true },
      { id: 'c-21', label: 'App Store / Play Store dev accounts', category: 'OTHER', plannedAmount: 600000, realAmount: 550000, isPaid: true },
      { id: 'c-22', label: 'Cartographie Mapbox API', category: 'API', plannedAmount: 800000, realAmount: 720000, isPaid: true },
      { id: 'c-23', label: 'Commission Commercial', category: 'SALES_COMMISSION', plannedAmount: 2450000, realAmount: 2450000, isPaid: true },
    ],
    realCosts: [
      { id: 'c-20', label: 'Développement Mobile (Andry)', category: 'DEV_COMMISSION', plannedAmount: 5000000, realAmount: 5000000, isPaid: true },
      { id: 'c-21', label: 'App Store / Play Store dev accounts', category: 'OTHER', plannedAmount: 600000, realAmount: 550000, isPaid: true },
      { id: 'c-22', label: 'Cartographie Mapbox API', category: 'API', plannedAmount: 800000, realAmount: 720000, isPaid: true },
      { id: 'c-23', label: 'Commission Commercial', category: 'SALES_COMMISSION', plannedAmount: 2450000, realAmount: 2450000, isPaid: true },
    ],
  },
  {
    id: 'prj-004',
    code: 'PRJ-2026-004',
    name: 'Refonte Site Web & Borne Interactive Ivato',
    category: 'WEBSITE',
    clientId: 'cli-ravinala',
    clientName: 'Ravinala Airports',
    sellingPrice: 12000000,
    status: 'IN_PROGRESS',
    startDate: '2026-06-15',
    deliveryDate: '2026-08-30',
    progressPercent: 90,
    totalCollected: 7200000,
    description: 'Interface d’information des vols en temps réel multilingue (FR/EN/MG).',
    plannedCosts: [
      { id: 'c-30', label: 'Intégration Frontend UI/UX', category: 'DEV_COMMISSION', plannedAmount: 2800000, realAmount: 2800000, isPaid: true },
      { id: 'c-31', label: 'Hébergement Vercel Pro & CDN', category: 'HOSTING', plannedAmount: 450000, realAmount: 450000, isPaid: true },
      { id: 'c-32', label: 'Nom de domaine .aero & SSL', category: 'DOMAIN', plannedAmount: 350000, realAmount: 320000, isPaid: true },
    ],
    realCosts: [
      { id: 'c-30', label: 'Intégration Frontend UI/UX', category: 'DEV_COMMISSION', plannedAmount: 2800000, realAmount: 2800000, isPaid: true },
      { id: 'c-31', label: 'Hébergement Vercel Pro & CDN', category: 'HOSTING', plannedAmount: 450000, realAmount: 450000, isPaid: true },
      { id: 'c-32', label: 'Nom de domaine .aero & SSL', category: 'DOMAIN', plannedAmount: 350000, realAmount: 320000, isPaid: true },
    ],
  },
  {
    id: 'prj-005',
    code: 'PRJ-2026-005',
    name: 'Système IoT & Télémétrie Laitière',
    category: 'EMBEDDED',
    clientId: 'cli-agri',
    clientName: 'AgriTech Vakinankaratra',
    sellingPrice: 18500000,
    status: 'IN_PROGRESS',
    startDate: '2026-07-01',
    deliveryDate: '2026-11-15',
    progressPercent: 40,
    totalCollected: 10000000,
    description: 'Capteurs connectés LoRaWAN température/acidité avec passerelle GSM.',
    plannedCosts: [
      { id: 'c-40', label: 'Capteurs & Boitiers Microcontrôleurs', category: 'HARDWARE', plannedAmount: 4200000, realAmount: 3900000, isPaid: true },
      { id: 'c-41', label: 'Firmware C++ & Embedded Dev', category: 'DEV_COMMISSION', plannedAmount: 3500000, realAmount: 2000000, isPaid: true },
      { id: 'c-42', label: 'Frais de transport & test Antsirabe', category: 'TRAVEL', plannedAmount: 800000, realAmount: 650000, isPaid: true },
    ],
    realCosts: [
      { id: 'c-40', label: 'Capteurs & Boitiers Microcontrôleurs', category: 'HARDWARE', plannedAmount: 4200000, realAmount: 3900000, isPaid: true },
      { id: 'c-41', label: 'Firmware C++ & Embedded Dev', category: 'DEV_COMMISSION', plannedAmount: 3500000, realAmount: 2000000, isPaid: true },
      { id: 'c-42', label: 'Frais de transport & test Antsirabe', category: 'TRAVEL', plannedAmount: 800000, realAmount: 650000, isPaid: true },
    ],
  },
];

export const INITIAL_INVOICES: Invoice[] = [
  {
    id: 'inv-000',
    invoiceNumber: 'FACTAVC N° 001',
    invoiceType: 'Facture Avance',
    clientId: 'cli-001',
    clientName: 'Name client',
    clientCompany: 'Entreprise Partenaire',
    clientPhone: '020 76 436 75',
    clientAddress: 'Antananarivo, Madagascar',
    projectName: 'Développement Site Web Dynamique',
    issueDate: '2026-07-31',
    dueDate: '2026-08-31',
    subtotal: 1000,
    taxRate: 0,
    taxAmount: 0,
    totalAmount: 1000,
    paidAmount: 400,
    balanceDue: 600,
    status: 'PARTIAL',
    paymentTerms: 'Avance 400 Ar à la commande, solde à la livraison',
    amountInWords: 'quatre-cent Ariary (400 Ar)',
    conditionsText: 'Eray Digital est responsable du renouvellement des sites en cas de piratage.',
    renewalTerms: '• Hébergement, nom de domaine, maintenance et sécurisation du site : 400 Ar/an/plateforme.',
    items: [
      {
        id: 'it-0',
        description: 'Développement d’un Site dynamique',
        subItems: [
          'Design 100% responsive (PC, Tablette, Mobile)',
          '2 adresses e-mail professionnelles',
          'Installation complète',
          'Site disponible en 1 langue',
          'Formulaire de contact et demande de devis.',
          '08 pages au choix avec optimisation SEO complète',
          'Hébergement offert pendant 1 an',
          'Maintenance et sécurisation pendant 1 an',
        ],
        quantity: 1,
        unitPrice: 1000,
        total: 1000,
      },
    ],
  },
  {
    id: 'inv-001',
    invoiceNumber: 'FAC-2026-001',
    invoiceType: 'Facture Acompte',
    clientId: 'cli-axian',
    clientName: 'Groupe Axian',
    clientCompany: 'Axian Telecom & Services',
    clientPhone: '+261 34 00 111 22',
    projectId: 'prj-001',
    projectName: 'Portail E-Commerce & Marketplace B2B',
    issueDate: '2026-06-01',
    dueDate: '2026-06-30',
    subtotal: 19000000,
    taxRate: 0,
    taxAmount: 0,
    totalAmount: 19000000,
    paidAmount: 19000000,
    balanceDue: 0,
    status: 'PAID',
    paymentTerms: 'Acompte 50% à la commande',
    amountInWords: 'dix-neuf millions d’Ariary (19 000 000 Ar)',
    conditionsText: 'Garantie logicielle 12 mois et support technique inclus.',
    renewalTerms: '• Infrastructure Cloud AWS & infogérance dédiée : 1 650 000 Ar/mois.',
    items: [
      {
        id: 'it-1',
        description: 'Acompte 50% - Architecture & Intégration Marketplace B2B',
        subItems: [
          'Design System Figma & maquettage interactif',
          'Module catalogue produits et gestion des stocks',
          'Intégration passerelles de paiement MVola & Orange Money',
        ],
        quantity: 1,
        unitPrice: 19000000,
        total: 19000000,
      },
    ],
  },
  {
    id: 'inv-002',
    invoiceNumber: 'FAC-2026-002',
    invoiceType: 'Facture Solde',
    clientId: 'cli-axian',
    clientName: 'Groupe Axian',
    clientCompany: 'Axian Telecom & Services',
    clientPhone: '+261 34 00 111 22',
    projectId: 'prj-001',
    projectName: 'Portail E-Commerce & Marketplace B2B',
    issueDate: '2026-07-20',
    dueDate: '2026-08-20',
    subtotal: 6000000,
    taxRate: 0,
    taxAmount: 0,
    totalAmount: 6000000,
    paidAmount: 6000000,
    balanceDue: 0,
    status: 'PAID',
    paymentTerms: 'Livrable Phase 1 validé',
    amountInWords: 'six millions d’Ariary (6 000 000 Ar)',
    items: [
      { id: 'it-2', description: 'Validation Sprint 2 - Passerelles de Paiement MVola/Orange', quantity: 1, unitPrice: 6000000, total: 6000000 },
    ],
  },
  {
    id: 'inv-003',
    invoiceNumber: 'FAC-2026-003',
    invoiceType: 'Facture Solde',
    clientId: 'cli-ravinala',
    clientName: 'Ravinala Airports',
    clientCompany: 'Aéroports de Madagascar',
    clientPhone: '+261 20 22 456 78',
    projectId: 'prj-004',
    projectName: 'Refonte Site Web & Borne Interactive Ivato',
    issueDate: '2026-07-10',
    dueDate: '2026-08-10',
    subtotal: 4800000,
    taxRate: 0,
    taxAmount: 0,
    totalAmount: 4800000,
    paidAmount: 0,
    balanceDue: 4800000,
    status: 'OVERDUE',
    paymentTerms: '30 jours date d’émission (Retard constaté)',
    amountInWords: 'quatre millions huit cent mille Ariary (4 800 000 Ar)',
    items: [
      { id: 'it-3', description: 'Solde final - Mise en production borne Ivato & Formation', quantity: 1, unitPrice: 4800000, total: 4800000 },
    ],
  },
  {
    id: 'inv-004',
    invoiceNumber: 'FAC-2026-004',
    invoiceType: 'Facture Standard',
    clientId: 'cli-star',
    clientName: 'Brasseries Star Madagascar',
    clientCompany: 'Groupe Castel / Star',
    clientPhone: '+261 20 22 234 56',
    projectId: 'prj-002',
    projectName: 'ERP Gestion Stocks & Logistique Brasserie',
    issueDate: '2026-08-01',
    dueDate: '2026-08-31',
    subtotal: 15000000,
    taxRate: 0,
    taxAmount: 0,
    totalAmount: 15000000,
    paidAmount: 0,
    balanceDue: 15000000,
    status: 'SENT',
    paymentTerms: 'Fin de mois',
    amountInWords: 'quinze millions d’Ariary (15 000 000 Ar)',
    items: [
      { id: 'it-4', description: 'Échéance Phase 2 - Module Stocks et Dépôts régionaux', quantity: 1, unitPrice: 15000000, total: 15000000 },
    ],
  },
  {
    id: 'inv-005',
    invoiceNumber: 'FAC-2026-005',
    invoiceType: 'Facture Acompte',
    clientId: 'cli-agri',
    clientName: 'AgriTech Vakinankaratra',
    clientCompany: 'Coopérative Laitière d’Antsirabe',
    clientPhone: '+261 34 55 678 90',
    projectId: 'prj-005',
    projectName: 'Système IoT & Télémétrie Laitière',
    issueDate: '2026-07-05',
    dueDate: '2026-08-05',
    subtotal: 10000000,
    taxRate: 0,
    taxAmount: 0,
    totalAmount: 10000000,
    paidAmount: 10000000,
    balanceDue: 0,
    status: 'PAID',
    paymentTerms: 'Acompte matériel initial',
    amountInWords: 'dix millions d’Ariary (10 000 000 Ar)',
    items: [
      { id: 'it-5', description: 'Acompte 50% + Achat capteurs IoT LoRaWAN', quantity: 1, unitPrice: 10000000, total: 10000000 },
    ],
  },
];

export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: 'tx-001',
    date: '2026-08-25',
    type: 'INCOME',
    amount: 6000000,
    accountId: 'acc-bni',
    category: 'PROJECT_INVOICE',
    description: 'Encaissement Facture FAC-2026-002 (Groupe Axian)',
    projectId: 'prj-001',
    projectName: 'Portail E-Commerce & Marketplace B2B',
    clientId: 'cli-axian',
    clientName: 'Groupe Axian',
    invoiceId: 'inv-002',
    status: 'REALIZED',
    createdAt: '2026-08-25T10:30:00Z',
    createdBy: 'Finance Manager',
  },
  {
    id: 'tx-002',
    date: '2026-08-24',
    type: 'EXPENSE',
    amount: 1650000,
    accountId: 'acc-bni',
    category: 'SERVER_CLOUD',
    description: 'Facturation AWS Cloud & RDS PostgreSQL',
    projectId: 'prj-001',
    projectName: 'Portail E-Commerce & Marketplace B2B',
    status: 'REALIZED',
    createdAt: '2026-08-24T14:15:00Z',
    createdBy: 'DevOps Lead',
  },
  {
    id: 'tx-003',
    date: '2026-08-20',
    type: 'TRANSFER',
    amount: 5000000,
    accountId: 'acc-bni',
    targetAccountId: 'acc-mvola',
    category: 'TRANSFER',
    description: 'Alimentation compte MVola pour paiements dévs et prestataires',
    status: 'REALIZED',
    createdAt: '2026-08-20T09:00:00Z',
    createdBy: 'Direction Eray',
  },
  {
    id: 'tx-004',
    date: '2026-08-18',
    type: 'EXPENSE',
    amount: 3200000,
    accountId: 'acc-mvola',
    category: 'COMMISSION',
    description: 'Versement commission Lead Dev (Andry)',
    projectId: 'prj-001',
    status: 'REALIZED',
    createdAt: '2026-08-18T16:45:00Z',
    createdBy: 'Finance Manager',
  },
  {
    id: 'tx-005',
    date: '2026-08-15',
    type: 'EXPENSE',
    amount: 2800000,
    accountId: 'acc-bni',
    category: 'OFFICE_RENT',
    description: 'Loyer bureaux Siège Ankorondrano + Connexion Fibre Telma',
    status: 'REALIZED',
    createdAt: '2026-08-15T08:30:00Z',
    createdBy: 'Admin',
  },
  {
    id: 'tx-006',
    date: '2026-08-10',
    type: 'INCOME',
    amount: 10000000,
    accountId: 'acc-bni',
    category: 'PROJECT_INVOICE',
    description: 'Encaissement Acompte AgriTech IoT',
    projectId: 'prj-005',
    projectName: 'Système IoT & Télémétrie Laitière',
    clientId: 'cli-agri',
    clientName: 'AgriTech Vakinankaratra',
    invoiceId: 'inv-005',
    status: 'REALIZED',
    createdAt: '2026-08-10T11:00:00Z',
    createdBy: 'Finance Manager',
  },
  {
    id: 'tx-007',
    date: '2026-08-05',
    type: 'EXPENSE',
    amount: 450000,
    accountId: 'acc-orange',
    category: 'MARKETING',
    description: 'Campagne sponsorisée LinkedIn & Facebook Ads Madagascar',
    status: 'REALIZED',
    createdAt: '2026-08-05T15:20:00Z',
    createdBy: 'Marketing',
  },
  {
    id: 'tx-008',
    date: '2026-08-02',
    type: 'TRANSFER',
    amount: 1000000,
    accountId: 'acc-bni',
    targetAccountId: 'acc-cash',
    category: 'TRANSFER',
    description: 'Retrait caisse pour menues dépenses et fournitures de bureau',
    status: 'REALIZED',
    createdAt: '2026-08-02T10:00:00Z',
    createdBy: 'Comptable',
  },
  {
    id: 'tx-009',
    date: '2026-08-01',
    type: 'EXPENSE',
    amount: 8500000,
    accountId: 'acc-bni',
    category: 'SALARY',
    description: 'Salaires équipe fixe Eray Digital (Juillet M-1)',
    status: 'REALIZED',
    createdAt: '2026-08-01T09:00:00Z',
    createdBy: 'Direction Eray',
  },
];

export const INITIAL_COMMISSIONS: Commission[] = [
  {
    id: 'com-001',
    beneficiaryName: 'Andry R. (Senior Fullstack Lead)',
    role: 'DEVELOPER',
    projectId: 'prj-001',
    projectName: 'Portail E-Commerce & Marketplace B2B',
    ruleType: 'PERCENTAGE',
    ruleValue: 20,
    calculatedAmount: 7600000,
    status: 'PAID',
    paidDate: '2026-08-18',
    notes: '20% sur encaissements validés',
  },
  {
    id: 'com-002',
    beneficiaryName: 'Tahina R. (Business Dev Manager)',
    role: 'SALES',
    projectId: 'prj-001',
    projectName: 'Portail E-Commerce & Marketplace B2B',
    ruleType: 'PERCENTAGE',
    ruleValue: 10,
    calculatedAmount: 3800000,
    status: 'PAID',
    paidDate: '2026-06-10',
    notes: '10% apporteur d’affaires contrat Axian',
  },
  {
    id: 'com-003',
    beneficiaryName: 'Mialy R. (Frontend & UX Lead)',
    role: 'DEVELOPER',
    projectId: 'prj-002',
    projectName: 'ERP Gestion Stocks & Logistique Brasserie',
    ruleType: 'FIXED',
    ruleValue: 5000000,
    calculatedAmount: 5000000,
    status: 'VALIDATED',
    notes: 'Forfait livrable modules logistique',
  },
  {
    id: 'com-004',
    beneficiaryName: 'Faly A. (Commercial Grands Comptes)',
    role: 'SALES',
    projectId: 'prj-002',
    projectName: 'ERP Gestion Stocks & Logistique Brasserie',
    ruleType: 'PERCENTAGE',
    ruleValue: 10,
    calculatedAmount: 4500000,
    status: 'PAID',
    paidDate: '2026-07-02',
  },
  {
    id: 'com-005',
    beneficiaryName: 'Hery T. (Embedded / IoT Eng.)',
    role: 'DEVELOPER',
    projectId: 'prj-005',
    projectName: 'Système IoT & Télémétrie Laitière',
    ruleType: 'PERCENTAGE',
    ruleValue: 18,
    calculatedAmount: 3330000,
    status: 'DRAFT',
    notes: 'En cours selon avancement des capteurs LoRaWAN',
  },
];

export const INITIAL_ALERTS: FinancialAlert[] = [
  {
    id: 'alt-001',
    type: 'OVERDUE_INVOICE',
    severity: 'CRITICAL',
    title: 'Impayé client : Ravinala Airports',
    description: 'La facture FAC-2026-003 d’un montant de 4 800 000 Ar est en retard de 14 jours.',
    date: '2026-08-10',
    targetDate: '2026-08-10',
    amount: 4800000,
    resolved: false,
    relatedEntityId: 'inv-003',
    relatedEntityType: 'INVOICE',
  },
  {
    id: 'alt-002',
    type: 'BUDGET_OVERRUN',
    severity: 'WARNING',
    title: 'Dépassement de coût Cloud : ERP Star',
    description: 'Les coûts d’infrastructure (2 850 000 Ar) dépassent le budget prévu initial de 650 000 Ar (+29%).',
    date: '2026-08-20',
    amount: 650000,
    resolved: false,
    relatedEntityId: 'prj-002',
    relatedEntityType: 'PROJECT',
  },
  {
    id: 'alt-003',
    type: 'OVERDRAFT_RISK',
    severity: 'WARNING',
    title: 'Projection Trésorerie : Solde MVola sous le seuil d’alerte',
    description: 'Les décaissements commissions prévus pourraient abaisser le solde sous 1 000 000 Ar d’ici le 15 septembre sans virement interne.',
    date: '2026-08-26',
    targetDate: '2026-09-15',
    resolved: false,
    relatedEntityId: 'acc-mvola',
    relatedEntityType: 'ACCOUNT',
  },
];

export const INITIAL_BUDGET_PERIODS: BudgetPeriod[] = [
  {
    id: 'bud-2026-06',
    month: '2026-06',
    targetRevenue: 28000000,
    targetExpense: 14000000,
    realizedRevenue: 31000000,
    realizedExpense: 13200000,
    initialBalance: 61170000,
    finalBalance: 78970000,
    isClosed: true,
    closedAt: '2026-06-30T23:59:59Z',
    closedBy: 'Direction Eray',
  },
  {
    id: 'bud-2026-07',
    month: '2026-07',
    targetRevenue: 30000000,
    targetExpense: 15000000,
    realizedRevenue: 32500000,
    realizedExpense: 14800000,
    initialBalance: 78970000,
    finalBalance: 96670000,
    isClosed: true,
    closedAt: '2026-07-31T23:59:59Z',
    closedBy: 'Direction Eray',
  },
  {
    id: 'bud-2026-08',
    month: '2026-08',
    targetRevenue: 35000000,
    targetExpense: 16000000,
    realizedRevenue: 16000000, // En cours
    realizedExpense: 8100000,
    initialBalance: 78970000,
    finalBalance: 78970000,
    isClosed: false,
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'log-001',
    timestamp: '2026-08-25T10:30:00Z',
    userName: 'Comptabilité Eray',
    action: 'Encaissement Facture',
    entityType: 'INVOICE',
    entityId: 'FAC-2026-002',
    details: 'Enregistrement paiement de 6 000 000 Ar sur BNI Madagascar',
    oldValue: 'Solde dû: 6 000 000 Ar',
    newValue: 'Solde dû: 0 Ar (Payée)',
  },
  {
    id: 'log-002',
    timestamp: '2026-08-20T09:00:00Z',
    userName: 'Direction Eray',
    action: 'Transfert Interne',
    entityType: 'TRANSFER',
    entityId: 'tx-003',
    details: 'Virement de 5 000 000 Ar de BNI Madagascar vers MVola Business',
  },
  {
    id: 'log-003',
    timestamp: '2026-08-18T16:45:00Z',
    userName: 'Finance Manager',
    action: 'Paiement Commission',
    entityType: 'COMMISSION',
    entityId: 'com-001',
    details: 'Validation et décaissement de 3 200 000 Ar pour Andry R.',
    oldValue: 'Statut: VALIDATED',
    newValue: 'Statut: PAID',
  },
  {
    id: 'log-004',
    timestamp: '2026-08-24T10:42:00Z',
    userName: 'Kiady (Admin)',
    action: 'Modification Montant Facture',
    entityType: 'INVOICE',
    entityId: 'FAC-2026-015',
    details: 'Mise à jour du montant pour ajustement du périmètre client',
    oldValue: '2 000 000 Ar',
    newValue: '2 200 000 Ar',
  },
];

export const INITIAL_SUPPLIERS = [
  {
    id: 'sup-aws',
    name: 'Amazon Web Services (AWS)',
    category: 'CLOUD' as const,
    contact: 'AWS Billing EMEA',
    email: 'billing@amazon.com',
    phone: '+1 206 266 1000',
    totalBilled: 12500000,
    totalPaid: 10850000,
    balanceDue: 1650000,
    status: 'ACTIVE' as const,
  },
  {
    id: 'sup-vercel',
    name: 'Vercel Inc.',
    category: 'HOSTING' as const,
    contact: 'Vercel Enterprise Sales',
    email: 'finance@vercel.com',
    phone: '+1 951 383 6898',
    totalBilled: 4500000,
    totalPaid: 4050000,
    balanceDue: 450000,
    status: 'ACTIVE' as const,
  },
  {
    id: 'sup-ovh',
    name: 'OVHcloud / Domains',
    category: 'DOMAIN' as const,
    contact: 'Support Domaines & DNS',
    email: 'support@ovh.com',
    phone: '+33 9 72 10 10 07',
    totalBilled: 2800000,
    totalPaid: 2480000,
    balanceDue: 320000,
    status: 'ACTIVE' as const,
  },
  {
    id: 'sup-telma',
    name: 'Telma Madagascar (Fibre Pro & SMS Gateway)',
    category: 'SAAS' as const,
    contact: 'Service Grands Comptes',
    email: 'b2b@telma.mg',
    phone: '+261 20 22 200 00',
    totalBilled: 8600000,
    totalPaid: 7800000,
    balanceDue: 800000,
    status: 'ACTIVE' as const,
  },
  {
    id: 'sup-dev-andry',
    name: 'Andry R. (Lead Architect Fullstack)',
    category: 'DEVELOPER' as const,
    contact: 'Andry Rabemananjara',
    email: 'andry.dev@eraydigital.mg',
    phone: '+261 34 88 123 99',
    totalBilled: 22000000,
    totalPaid: 18800000,
    balanceDue: 3200000,
    status: 'ACTIVE' as const,
  },
];

export const INITIAL_FIXED_EXPENSES = [
  {
    id: 'fe-01',
    label: 'Loyer des Bureaux (Ankorondrano)',
    category: 'RENT' as const,
    amount: 3200000,
    frequency: 'MONTHLY' as const,
    dueDay: 5,
    assignedTo: 'Direction Générale',
    paymentAccountId: 'acc-bni',
    autoGenerateNextDue: true,
    status: 'ACTIVE' as const,
  },
  {
    id: 'fe-02',
    label: 'Fibre Optique Dédiée Telma Pro',
    category: 'WIFI' as const,
    amount: 650000,
    frequency: 'MONTHLY' as const,
    dueDay: 10,
    assignedTo: 'Finance / IT',
    paymentAccountId: 'acc-mvola',
    autoGenerateNextDue: true,
    status: 'ACTIVE' as const,
  },
  {
    id: 'fe-03',
    label: 'Facture Jirama Électricité & Eau',
    category: 'ELECTRICITY' as const,
    amount: 850000,
    frequency: 'MONTHLY' as const,
    dueDay: 15,
    assignedTo: 'Office Manager',
    paymentAccountId: 'acc-bni',
    autoGenerateNextDue: true,
    status: 'ACTIVE' as const,
  },
  {
    id: 'fe-04',
    label: 'Salaires Fixes & Charges Sociales de Base',
    category: 'SALARIES' as const,
    amount: 8500000,
    frequency: 'MONTHLY' as const,
    dueDay: 28,
    assignedTo: 'RH & Direction',
    paymentAccountId: 'acc-bni',
    autoGenerateNextDue: true,
    status: 'ACTIVE' as const,
  },
  {
    id: 'fe-05',
    label: 'Abonnements Outils (GitHub Enterprise, Figma, Slack)',
    category: 'SAAS' as const,
    amount: 950000,
    frequency: 'MONTHLY' as const,
    dueDay: 1,
    assignedTo: 'Lead Tech',
    paymentAccountId: 'acc-bmoi',
    autoGenerateNextDue: true,
    status: 'ACTIVE' as const,
  },
  {
    id: 'fe-06',
    label: 'Honoraires Cabinet d’Expertise Comptable',
    category: 'ACCOUNTING' as const,
    amount: 750000,
    frequency: 'MONTHLY' as const,
    dueDay: 20,
    assignedTo: 'Finance',
    paymentAccountId: 'acc-bni',
    autoGenerateNextDue: true,
    status: 'ACTIVE' as const,
  },
];

export const INITIAL_USERS = [
  { id: 'usr-1', name: 'Kiady (Admin)', email: 'kiady@eraydigital.mg', role: 'ADMIN' as const },
  { id: 'usr-2', name: 'Direction Eray', email: 'direction@eraydigital.mg', role: 'DIRECTION' as const },
  { id: 'usr-3', name: 'Finance & Trésorerie', email: 'finance@eraydigital.mg', role: 'FINANCE' as const },
  { id: 'usr-4', name: 'Auditeur Externe', email: 'audit@eraydigital.mg', role: 'READONLY' as const },
];

// ==========================================
// PLAN COMPTABLE GÉNÉRAL (PCG 2005 / MADAGASCAR)
// ==========================================

export const INITIAL_PCG_ACCOUNTS = [
  // Classe 1 : Comptes de capitaux
  { code: '101', name: 'Capital social', classNum: 1 as const, category: 'CAPITAUX_PROPRES' as const, type: 'CREDIT_NORMAL' as const, description: 'Capital initial apporté par les fondateurs' },
  { code: '106', name: 'Réserves légales et statutaires', classNum: 1 as const, category: 'CAPITAUX_PROPRES' as const, type: 'CREDIT_NORMAL' as const, description: 'Bénéfices conservés en réserve' },
  { code: '120', name: 'Résultat de l’exercice (Bénéfice)', classNum: 1 as const, category: 'CAPITAUX_PROPRES' as const, type: 'CREDIT_NORMAL' as const, description: 'Solde créditeur net du compte de résultat' },
  { code: '129', name: 'Résultat de l’exercice (Perte)', classNum: 1 as const, category: 'CAPITAUX_PROPRES' as const, type: 'DEBIT_NORMAL' as const, description: 'Solde débiteur net du compte de résultat' },
  { code: '164', name: 'Emprunts auprès des établissements de crédit', classNum: 1 as const, category: 'CAPITAUX_PROPRES' as const, type: 'CREDIT_NORMAL' as const, description: 'Dettes bancaires à moyen et long terme' },
  { code: '455', name: 'Associés - Comptes courants', classNum: 1 as const, category: 'CAPITAUX_PROPRES' as const, type: 'CREDIT_NORMAL' as const, description: 'Avances de trésorerie des associés' },

  // Classe 2 : Comptes d'immobilisations
  { code: '205', name: 'Concessions, brevets, licences logicielles', classNum: 2 as const, category: 'ACTIF_IMMOBILISE' as const, type: 'DEBIT_NORMAL' as const, description: 'Droits logiciels et propriété intellectuelle' },
  { code: '215', name: 'Installations techniques et équipements', classNum: 2 as const, category: 'ACTIF_IMMOBILISE' as const, type: 'DEBIT_NORMAL' as const, description: 'Serveurs physiques, routeurs et matériel réseau' },
  { code: '2182', name: 'Matériel de transport', classNum: 2 as const, category: 'ACTIF_IMMOBILISE' as const, type: 'DEBIT_NORMAL' as const, description: 'Véhicules et utilitaires d’intervention' },
  { code: '2183', name: 'Matériel informatique et télécoms', classNum: 2 as const, category: 'ACTIF_IMMOBILISE' as const, type: 'DEBIT_NORMAL' as const, description: 'Postes de dev Mac/PC, moniteurs, laptops' },
  { code: '2184', name: 'Mobilier de bureau et agencements', classNum: 2 as const, category: 'ACTIF_IMMOBILISE' as const, type: 'DEBIT_NORMAL' as const, description: 'Tables, chaises ergonomiques, déco siège' },

  // Classe 3 : Comptes de stocks
  { code: '311', name: 'Matières premières et composants IoT', classNum: 3 as const, category: 'STOCKS' as const, type: 'DEBIT_NORMAL' as const, description: 'Cartes électroniques, capteurs pour prototypes' },
  { code: '355', name: 'Progiciels et solutions packagées', classNum: 3 as const, category: 'STOCKS' as const, type: 'DEBIT_NORMAL' as const, description: 'Modules logiciels prêts à la vente' },

  // Classe 4 : Comptes de tiers
  { code: '401', name: 'Fournisseurs d’exploitation', classNum: 4 as const, category: 'TIERS' as const, type: 'CREDIT_NORMAL' as const, description: 'Dettes fournisseurs (SaaS, serveurs, hébergeurs)' },
  { code: '411', name: 'Clients', classNum: 4 as const, category: 'TIERS' as const, type: 'DEBIT_NORMAL' as const, description: 'Créances clients sur prestations et projets' },
  { code: '421', name: 'Personnel - Rémunérations dues (Commissions & Salaires)', classNum: 4 as const, category: 'TIERS' as const, type: 'CREDIT_NORMAL' as const, description: 'Commissions et salaires à verser' },
  { code: '431', name: 'Sécurité sociale et organismes sociaux (CNaPS / OSTIE)', classNum: 4 as const, category: 'TIERS' as const, type: 'CREDIT_NORMAL' as const, description: 'Cotisations sociales obligatoires' },
  { code: '445', name: 'État - Taxes et impôts à payer', classNum: 4 as const, category: 'TIERS' as const, type: 'CREDIT_NORMAL' as const, description: 'TVA, acomptes IR / IBS, taxe synthétique' },

  // Classe 5 : Comptes financiers et trésorerie
  { code: '512', name: 'Banque (BNI / BMOI Madagascar)', classNum: 5 as const, category: 'TRESORERIE' as const, type: 'DEBIT_NORMAL' as const, description: 'Comptes bancaires professionnels' },
  { code: '514', name: 'Comptes Mobile Money (MVola / Orange Money)', classNum: 5 as const, category: 'TRESORERIE' as const, type: 'DEBIT_NORMAL' as const, description: 'Comptes marchands digitaux' },
  { code: '530', name: 'Caisse centrale espèces', classNum: 5 as const, category: 'TRESORERIE' as const, type: 'DEBIT_NORMAL' as const, description: 'Disponibilités physiques au siège' },
  { code: '580', name: 'Virements internes de fonds', classNum: 5 as const, category: 'TRESORERIE' as const, type: 'DEBIT_NORMAL' as const, description: 'Compte de passage pour transferts inter-comptes' },

  // Classe 6 : Comptes de charges
  { code: '607', name: 'Achats de matériel et marchandises', classNum: 6 as const, category: 'CHARGES' as const, type: 'DEBIT_NORMAL' as const, description: 'Achats directs matériels, composants' },
  { code: '613', name: 'Locations immobilières (Loyer siège)', classNum: 6 as const, category: 'CHARGES' as const, type: 'DEBIT_NORMAL' as const, description: 'Loyer des bureaux Ankorondrano' },
  { code: '615', name: 'Entretien, réparations et maintenance', classNum: 6 as const, category: 'CHARGES' as const, type: 'DEBIT_NORMAL' as const, description: 'Entretien local et matériel' },
  { code: '621', name: 'Commissions et sous-traitance tech', classNum: 6 as const, category: 'CHARGES' as const, type: 'DEBIT_NORMAL' as const, description: 'Commissions développeurs et commerciaux' },
  { code: '622', name: 'Rémunérations d’intermédiaires et honoraires', classNum: 6 as const, category: 'CHARGES' as const, type: 'DEBIT_NORMAL' as const, description: 'Expertise comptable, conseils juridiques' },
  { code: '626', name: 'Frais postaux et télécoms (Fibre, Cloud AWS, SaaS)', classNum: 6 as const, category: 'CHARGES' as const, type: 'DEBIT_NORMAL' as const, description: 'Serveurs, internet et licences' },
  { code: '641', name: 'Rémunérations du personnel (Salaires fixes)', classNum: 6 as const, category: 'CHARGES' as const, type: 'DEBIT_NORMAL' as const, description: 'Masse salariale fixe de l’équipe' },
  { code: '645', name: 'Charges de sécurité sociale et de prévoyance', classNum: 6 as const, category: 'CHARGES' as const, type: 'DEBIT_NORMAL' as const, description: 'Charges patronales CNaPS / OSTIE' },

  // Classe 7 : Comptes de produits
  { code: '706', name: 'Prestations de services (Développement web, mobile, SaaS)', classNum: 7 as const, category: 'PRODUITS' as const, type: 'CREDIT_NORMAL' as const, description: 'Chiffre d’affaires services numériques' },
  { code: '707', name: 'Vente de progiciels et matériels informatiques', classNum: 7 as const, category: 'PRODUITS' as const, type: 'CREDIT_NORMAL' as const, description: 'Vente de licences et solutions packagées' },
  { code: '708', name: 'Produits des activités annexes (Maintenance, Conseil, Audit)', classNum: 7 as const, category: 'PRODUITS' as const, type: 'CREDIT_NORMAL' as const, description: 'Contrats récurrents de maintenance' },
  { code: '758', name: 'Produits exceptionnels divers', classNum: 7 as const, category: 'PRODUITS' as const, type: 'CREDIT_NORMAL' as const, description: 'Gains divers hors exploitation courante' },
];

export const INITIAL_JOURNAL_ENTRIES = [
  {
    id: 'ecr-001',
    entryNumber: 'ECR-2026-001',
    date: '2026-08-05',
    pieceRef: 'STATUTS-APPORT-01',
    label: 'Constitution du capital social de départ Eray Digital',
    journalType: 'OPERATIONS_DIVERSES' as const,
    lines: [
      { id: 'l1', accountCode: '512', accountName: 'Banque (BNI Madagascar)', debit: 25000000, credit: 0 },
      { id: 'l2', accountCode: '101', accountName: 'Capital social', debit: 0, credit: 25000000 },
    ],
    totalDebit: 25000000,
    totalCredit: 25000000,
    isBalanced: true,
  },
  {
    id: 'ecr-002',
    entryNumber: 'ECR-2026-002',
    date: '2026-08-10',
    pieceRef: 'CONTRAT-EMPRUNT-BNI',
    label: 'Déblocage emprunt bancaire d’investissement BNI',
    journalType: 'BANQUE' as const,
    lines: [
      { id: 'l3', accountCode: '512', accountName: 'Banque (BNI Madagascar)', debit: 50000000, credit: 0 },
      { id: 'l4', accountCode: '164', accountName: 'Emprunts auprès des établissements de crédit', debit: 0, credit: 50000000 },
    ],
    totalDebit: 50000000,
    totalCredit: 50000000,
    isBalanced: true,
  },
  {
    id: 'ecr-003',
    entryNumber: 'ECR-2026-003',
    date: '2026-08-12',
    pieceRef: 'FACT-EQUIP-042',
    label: 'Acquisition matériel informatique serveurs & transport',
    journalType: 'ACHATS' as const,
    lines: [
      { id: 'l5', accountCode: '2182', accountName: 'Matériel de transport', debit: 15000000, credit: 0 },
      { id: 'l6', accountCode: '2183', accountName: 'Matériel informatique et télécoms', debit: 1000000, credit: 0 },
      { id: 'l7', accountCode: '512', accountName: 'Banque (BNI Madagascar)', debit: 0, credit: 16000000 },
    ],
    totalDebit: 16000000,
    totalCredit: 16000000,
    isBalanced: true,
  },
  {
    id: 'ecr-004',
    entryNumber: 'ECR-2026-004',
    date: '2026-08-13',
    pieceRef: 'FACT-FOURN-01',
    label: 'Achat de marchandises & licences (Facture Fournisseur N°1)',
    journalType: 'ACHATS' as const,
    lines: [
      { id: 'l8', accountCode: '607', accountName: 'Achats de matériel et marchandises', debit: 12500000, credit: 0 },
      { id: 'l9', accountCode: '512', accountName: 'Banque (BNI Madagascar)', debit: 0, credit: 12500000 },
    ],
    totalDebit: 12500000,
    totalCredit: 12500000,
    isBalanced: true,
  },
  {
    id: 'ecr-005',
    entryNumber: 'ECR-2026-005',
    date: '2026-08-20',
    pieceRef: 'FAC-2026-001',
    label: 'Facturation prestation client Groupe Axian (dont part à crédit)',
    journalType: 'VENTES' as const,
    lines: [
      { id: 'l10', accountCode: '411', accountName: 'Clients (Créance)', debit: 5000000, credit: 0 },
      { id: 'l11', accountCode: '512', accountName: 'Banque (BNI Madagascar)', debit: 13000000, credit: 0 },
      { id: 'l12', accountCode: '706', accountName: 'Prestations de services (Ventes)', debit: 0, credit: 18000000 },
    ],
    totalDebit: 18000000,
    totalCredit: 18000000,
    isBalanced: true,
  },
  {
    id: 'ecr-006',
    entryNumber: 'ECR-2026-006',
    date: '2026-08-22',
    pieceRef: 'FACT-FOURN-02',
    label: 'Achat de marchandises à crédit (Facture Fournisseur N°2)',
    journalType: 'ACHATS' as const,
    lines: [
      { id: 'l13', accountCode: '607', accountName: 'Achats de matériel et marchandises', debit: 5000000, credit: 0 },
      { id: 'l14', accountCode: '401', accountName: 'Fournisseurs d’exploitation', debit: 0, credit: 5000000 },
    ],
    totalDebit: 5000000,
    totalCredit: 5000000,
    isBalanced: true,
  },
];


